// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-DrUuGk5Aou4G-3GYk0EA-HV0PYI6wt4',
    appId: '1:189846349067:web:d656f68e6401d33c8f2e0e',
    messagingSenderId: '189846349067',
    projectId: 'rootrails-4c8b6',
    authDomain: 'rootrails-4c8b6.firebaseapp.com',
    storageBucket: 'rootrails-4c8b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvzqLlz03Z45UnmxVxG6K4dDe-3sycD_o',
    appId: '1:189846349067:android:29bedd764a3fd5f88f2e0e',
    messagingSenderId: '189846349067',
    projectId: 'rootrails-4c8b6',
    storageBucket: 'rootrails-4c8b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS0F7tcH2VIONa95E1veeoWCheTo599Ck',
    appId: '1:189846349067:ios:bc43eb0618c16abd8f2e0e',
    messagingSenderId: '189846349067',
    projectId: 'rootrails-4c8b6',
    storageBucket: 'rootrails-4c8b6.firebasestorage.app',
    iosBundleId: 'com.example.rootrails',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS0F7tcH2VIONa95E1veeoWCheTo599Ck',
    appId: '1:189846349067:ios:bc43eb0618c16abd8f2e0e',
    messagingSenderId: '189846349067',
    projectId: 'rootrails-4c8b6',
    storageBucket: 'rootrails-4c8b6.firebasestorage.app',
    iosBundleId: 'com.example.rootrails',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-DrUuGk5Aou4G-3GYk0EA-HV0PYI6wt4',
    appId: '1:189846349067:web:78759391f6b863748f2e0e',
    messagingSenderId: '189846349067',
    projectId: 'rootrails-4c8b6',
    authDomain: 'rootrails-4c8b6.firebaseapp.com',
    storageBucket: 'rootrails-4c8b6.firebasestorage.app',
  );
}
